language: go

go:
    - 1.14.x

services:
    - redis-server

env:
    - TEST_REDIS_ADDRESSES=localhost:6379

before_script:
    - sh -c "sleep 5"  # give Redis a(n additional) chance to start

script:
    - go test -v -race ./...
